<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code');
            $table->string('name');
        });

        // Insert the countries values.
        DB::table('countries')->insert(
            array(
                array('code' => 'AD', 'name' => 'Andorra'),
                array('code' => 'AE', 'name' => 'United Arab Emirates'),
                array('code' => 'AF', 'name' => 'Afghanistan'),
                array('code' => 'AG', 'name' => 'Antigua and Barbuda'),
                array('code' => 'AI', 'name' => 'Anguilla'),
                array('code' => 'AL', 'name' => 'Albania'),
                array('code' => 'AM', 'name' => 'Armenia'),
                array('code' => 'AO', 'name' => 'Angola'),
                array('code' => 'AQ', 'name' => 'Antarctica'),
                array('code' => 'AR', 'name' => 'Argentina'),
                array('code' => 'AS', 'name' => 'American Samoa'),
                array('code' => 'AT', 'name' => 'Austria'),
                array('code' => 'AU', 'name' => 'Australia'),
                array('code' => 'AW', 'name' => 'Aruba'),
                array('code' => 'AX', 'name' => 'Åland'),
                array('code' => 'AZ', 'name' => 'Azerbaijan'),
                array('code' => 'BA', 'name' => 'Bosnia and Herzegovina'),
                array('code' => 'BB', 'name' => 'Barbados'),
                array('code' => 'BD', 'name' => 'Bangladesh'),
                array('code' => 'BE', 'name' => 'Belgium'),
                array('code' => 'BF', 'name' => 'Burkina Faso'),
                array('code' => 'BG', 'name' => 'Bulgaria'),
                array('code' => 'BH', 'name' => 'Bahrain'),
                array('code' => 'BI', 'name' => 'Burundi'),
                array('code' => 'BJ', 'name' => 'Benin'),
                array('code' => 'BL', 'name' => 'Saint Barthélemy'),
                array('code' => 'BM', 'name' => 'Bermuda'),
                array('code' => 'BN', 'name' => 'Brunei'),
                array('code' => 'BO', 'name' => 'Bolivia'),
                array('code' => 'BQ', 'name' => 'Bonaire'),
                array('code' => 'BR', 'name' => 'Brazil'),
                array('code' => 'BS', 'name' => 'Bahamas'),
                array('code' => 'BT', 'name' => 'Bhutan'),
                array('code' => 'BV', 'name' => 'Bouvet Island'),
                array('code' => 'BW', 'name' => 'Botswana'),
                array('code' => 'BY', 'name' => 'Belarus'),
                array('code' => 'BZ', 'name' => 'Belize'),
                array('code' => 'CA', 'name' => 'Canada'),
                array('code' => 'CC', 'name' => 'Cocos [Keeling] Islands'),
                array('code' => 'CD', 'name' => 'Democratic Republic of the Congo'),
                array('code' => 'CF', 'name' => 'Central African Republic'),
                array('code' => 'CG', 'name' => 'Republic of the Congo'),
                array('code' => 'CH', 'name' => 'Switzerland'),
                array('code' => 'CI', 'name' => 'Ivory Coast'),
                array('code' => 'CK', 'name' => 'Cook Islands'),
                array('code' => 'CL', 'name' => 'Chile'),
                array('code' => 'CM', 'name' => 'Cameroon'),
                array('code' => 'CN', 'name' => 'China'),
                array('code' => 'CO', 'name' => 'Colombia'),
                array('code' => 'CR', 'name' => 'Costa Rica'),
                array('code' => 'CU', 'name' => 'Cuba'),
                array('code' => 'CV', 'name' => 'Cape Verde'),
                array('code' => 'CW', 'name' => 'Curacao'),
                array('code' => 'CX', 'name' => 'Christmas Island'),
                array('code' => 'CY', 'name' => 'Cyprus'),
                array('code' => 'CZ', 'name' => 'Czechia'),
                array('code' => 'DE', 'name' => 'Germany'),
                array('code' => 'DJ', 'name' => 'Djibouti'),
                array('code' => 'DK', 'name' => 'Denmark'),
                array('code' => 'DM', 'name' => 'Dominica'),
                array('code' => 'DO', 'name' => 'Dominican Republic'),
                array('code' => 'DZ', 'name' => 'Algeria'),
                array('code' => 'EC', 'name' => 'Ecuador'),
                array('code' => 'EE', 'name' => 'Estonia'),
                array('code' => 'EG', 'name' => 'Egypt'),
                array('code' => 'EH', 'name' => 'Western Sahara'),
                array('code' => 'ER', 'name' => 'Eritrea'),
                array('code' => 'ES', 'name' => 'Spain'),
                array('code' => 'ET', 'name' => 'Ethiopia'),
                array('code' => 'FI', 'name' => 'Finland'),
                array('code' => 'FJ', 'name' => 'Fiji'),
                array('code' => 'FK', 'name' => 'Falkland Islands'),
                array('code' => 'FM', 'name' => 'Micronesia'),
                array('code' => 'FO', 'name' => 'Faroe Islands'),
                array('code' => 'FR', 'name' => 'France'),
                array('code' => 'GA', 'name' => 'Gabon'),
                array('code' => 'GB', 'name' => 'United Kingdom'),
                array('code' => 'GD', 'name' => 'Grenada'),
                array('code' => 'GE', 'name' => 'Georgia'),
                array('code' => 'GF', 'name' => 'French Guiana'),
                array('code' => 'GG', 'name' => 'Guernsey'),
                array('code' => 'GH', 'name' => 'Ghana'),
                array('code' => 'GI', 'name' => 'Gibraltar'),
                array('code' => 'GL', 'name' => 'Greenland'),
                array('code' => 'GM', 'name' => 'Gambia'),
                array('code' => 'GN', 'name' => 'Guinea'),
                array('code' => 'GP', 'name' => 'Guadeloupe'),
                array('code' => 'GQ', 'name' => 'Equatorial Guinea'),
                array('code' => 'GR', 'name' => 'Greece'),
                array('code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'),
                array('code' => 'GT', 'name' => 'Guatemala'),
                array('code' => 'GU', 'name' => 'Guam'),
                array('code' => 'GW', 'name' => 'Guinea-Bissau'),
                array('code' => 'GY', 'name' => 'Guyana'),
                array('code' => 'HK', 'name' => 'Hong Kong'),
                array('code' => 'HM', 'name' => 'Heard Island and McDonald Islands'),
                array('code' => 'HN', 'name' => 'Honduras'),
                array('code' => 'HR', 'name' => 'Croatia'),
                array('code' => 'HT', 'name' => 'Haiti'),
                array('code' => 'HU', 'name' => 'Hungary'),
                array('code' => 'ID', 'name' => 'Indonesia'),
                array('code' => 'IE', 'name' => 'Ireland'),
                array('code' => 'IL', 'name' => 'Israel'),
                array('code' => 'IM', 'name' => 'Isle of Man'),
                array('code' => 'IN', 'name' => 'India'),
                array('code' => 'IO', 'name' => 'British Indian Ocean Territory'),
                array('code' => 'IQ', 'name' => 'Iraq'),
                array('code' => 'IR', 'name' => 'Iran'),
                array('code' => 'IS', 'name' => 'Iceland'),
                array('code' => 'IT', 'name' => 'Italy'),
                array('code' => 'JE', 'name' => 'Jersey'),
                array('code' => 'JM', 'name' => 'Jamaica'),
                array('code' => 'JO', 'name' => 'Jordan'),
                array('code' => 'JP', 'name' => 'Japan'),
                array('code' => 'KE', 'name' => 'Kenya'),
                array('code' => 'KG', 'name' => 'Kyrgyzstan'),
                array('code' => 'KH', 'name' => 'Cambodia'),
                array('code' => 'KI', 'name' => 'Kiribati'),
                array('code' => 'KM', 'name' => 'Comoros'),
                array('code' => 'KN', 'name' => 'Saint Kitts and Nevis'),
                array('code' => 'KP', 'name' => 'North Korea'),
                array('code' => 'KR', 'name' => 'South Korea'),
                array('code' => 'KW', 'name' => 'Kuwait'),
                array('code' => 'KY', 'name' => 'Cayman Islands'),
                array('code' => 'KZ', 'name' => 'Kazakhstan'),
                array('code' => 'LA', 'name' => 'Laos'),
                array('code' => 'LB', 'name' => 'Lebanon'),
                array('code' => 'LC', 'name' => 'Saint Lucia'),
                array('code' => 'LI', 'name' => 'Liechtenstein'),
                array('code' => 'LK', 'name' => 'Sri Lanka'),
                array('code' => 'LR', 'name' => 'Liberia'),
                array('code' => 'LS', 'name' => 'Lesotho'),
                array('code' => 'LT', 'name' => 'Lithuania'),
                array('code' => 'LU', 'name' => 'Luxembourg'),
                array('code' => 'LV', 'name' => 'Latvia'),
                array('code' => 'LY', 'name' => 'Libya'),
                array('code' => 'MA', 'name' => 'Morocco'),
                array('code' => 'MC', 'name' => 'Monaco'),
                array('code' => 'MD', 'name' => 'Moldova'),
                array('code' => 'ME', 'name' => 'Montenegro'),
                array('code' => 'MF', 'name' => 'Saint Martin'),
                array('code' => 'MG', 'name' => 'Madagascar'),
                array('code' => 'MH', 'name' => 'Marshall Islands'),
                array('code' => 'MK', 'name' => 'Macedonia'),
                array('code' => 'ML', 'name' => 'Mali'),
                array('code' => 'MM', 'name' => 'Myanmar [Burma]'),
                array('code' => 'MN', 'name' => 'Mongolia'),
                array('code' => 'MO', 'name' => 'Macao'),
                array('code' => 'MP', 'name' => 'Northern Mariana Islands'),
                array('code' => 'MQ', 'name' => 'Martinique'),
                array('code' => 'MR', 'name' => 'Mauritania'),
                array('code' => 'MS', 'name' => 'Montserrat'),
                array('code' => 'MT', 'name' => 'Malta'),
                array('code' => 'MU', 'name' => 'Mauritius'),
                array('code' => 'MV', 'name' => 'Maldives'),
                array('code' => 'MW', 'name' => 'Malawi'),
                array('code' => 'MX', 'name' => 'Mexico'),
                array('code' => 'MY', 'name' => 'Malaysia'),
                array('code' => 'MZ', 'name' => 'Mozambique'),
                array('code' => 'NA', 'name' => 'Namibia'),
                array('code' => 'NC', 'name' => 'New Caledonia'),
                array('code' => 'NE', 'name' => 'Niger'),
                array('code' => 'NF', 'name' => 'Norfolk Island'),
                array('code' => 'NG', 'name' => 'Nigeria'),
                array('code' => 'NI', 'name' => 'Nicaragua'),
                array('code' => 'NL', 'name' => 'Netherlands'),
                array('code' => 'NO', 'name' => 'Norway'),
                array('code' => 'NP', 'name' => 'Nepal'),
                array('code' => 'NR', 'name' => 'Nauru'),
                array('code' => 'NU', 'name' => 'Niue'),
                array('code' => 'NZ', 'name' => 'New Zealand'),
                array('code' => 'OM', 'name' => 'Oman'),
                array('code' => 'PA', 'name' => 'Panama'),
                array('code' => 'PE', 'name' => 'Peru'),
                array('code' => 'PF', 'name' => 'French Polynesia'),
                array('code' => 'PG', 'name' => 'Papua New Guinea'),
                array('code' => 'PH', 'name' => 'Philippines'),
                array('code' => 'PK', 'name' => 'Pakistan'),
                array('code' => 'PL', 'name' => 'Poland'),
                array('code' => 'PM', 'name' => 'Saint Pierre and Miquelon'),
                array('code' => 'PN', 'name' => 'Pitcairn Islands'),
                array('code' => 'PR', 'name' => 'Puerto Rico'),
                array('code' => 'PS', 'name' => 'Palestine'),
                array('code' => 'PT', 'name' => 'Portugal'),
                array('code' => 'PW', 'name' => 'Palau'),
                array('code' => 'PY', 'name' => 'Paraguay'),
                array('code' => 'QA', 'name' => 'Qatar'),
                array('code' => 'RE', 'name' => 'Réunion'),
                array('code' => 'RO', 'name' => 'Romania'),
                array('code' => 'RS', 'name' => 'Serbia'),
                array('code' => 'RU', 'name' => 'Russia'),
                array('code' => 'RW', 'name' => 'Rwanda'),
                array('code' => 'SA', 'name' => 'Saudi Arabia'),
                array('code' => 'SB', 'name' => 'Solomon Islands'),
                array('code' => 'SC', 'name' => 'Seychelles'),
                array('code' => 'SD', 'name' => 'Sudan'),
                array('code' => 'SE', 'name' => 'Sweden'),
                array('code' => 'SG', 'name' => 'Singapore'),
                array('code' => 'SH', 'name' => 'Saint Helena'),
                array('code' => 'SI', 'name' => 'Slovenia'),
                array('code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'),
                array('code' => 'SK', 'name' => 'Slovakia'),
                array('code' => 'SL', 'name' => 'Sierra Leone'),
                array('code' => 'SM', 'name' => 'San Marino'),
                array('code' => 'SN', 'name' => 'Senegal'),
                array('code' => 'SO', 'name' => 'Somalia'),
                array('code' => 'SR', 'name' => 'Suriname'),
                array('code' => 'SS', 'name' => 'South Sudan'),
                array('code' => 'ST', 'name' => 'São Tomé and Príncipe'),
                array('code' => 'SV', 'name' => 'El Salvador'),
                array('code' => 'SX', 'name' => 'Sint Maarten'),
                array('code' => 'SY', 'name' => 'Syria'),
                array('code' => 'SZ', 'name' => 'Swaziland'),
                array('code' => 'TC', 'name' => 'Turks and Caicos Islands'),
                array('code' => 'TD', 'name' => 'Chad'),
                array('code' => 'TF', 'name' => 'French Southern Territories'),
                array('code' => 'TG', 'name' => 'Togo'),
                array('code' => 'TH', 'name' => 'Thailand'),
                array('code' => 'TJ', 'name' => 'Tajikistan'),
                array('code' => 'TK', 'name' => 'Tokelau'),
                array('code' => 'TL', 'name' => 'East Timor'),
                array('code' => 'TM', 'name' => 'Turkmenistan'),
                array('code' => 'TN', 'name' => 'Tunisia'),
                array('code' => 'TO', 'name' => 'Tonga'),
                array('code' => 'TR', 'name' => 'Turkey'),
                array('code' => 'TT', 'name' => 'Trinidad and Tobago'),
                array('code' => 'TV', 'name' => 'Tuvalu'),
                array('code' => 'TW', 'name' => 'Taiwan'),
                array('code' => 'TZ', 'name' => 'Tanzania'),
                array('code' => 'UA', 'name' => 'Ukraine'),
                array('code' => 'UG', 'name' => 'Uganda'),
                array('code' => 'UM', 'name' => 'U.S. Minor Outlying Islands'),
                array('code' => 'US', 'name' => 'United States'),
                array('code' => 'UY', 'name' => 'Uruguay'),
                array('code' => 'UZ', 'name' => 'Uzbekistan'),
                array('code' => 'VA', 'name' => 'Vatican City'),
                array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'),
                array('code' => 'VE', 'name' => 'Venezuela'),
                array('code' => 'VG', 'name' => 'British Virgin Islands'),
                array('code' => 'VI', 'name' => 'U.S. Virgin Islands'),
                array('code' => 'VN', 'name' => 'Vietnam'),
                array('code' => 'VU', 'name' => 'Vanuatu'),
                array('code' => 'WF', 'name' => 'Wallis and Futuna'),
                array('code' => 'WS', 'name' => 'Samoa'),
                array('code' => 'XK', 'name' => 'Kosovo'),
                array('code' => 'YE', 'name' => 'Yemen'),
                array('code' => 'YT', 'name' => 'Mayotte'),
                array('code' => 'ZA', 'name' => 'South Africa'),
                array('code' => 'ZM', 'name' => 'Zambia'),
                array('code' => 'ZW', 'name' => 'Zimbabwe')
            )
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
